name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test
    
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          package: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Get config file
        env:
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_API }}
        run: |
          echo $EAS_GOOGLE_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build and submit
        run: eas build --platform android --non-interactive --profile production --non-interactive --auto-submit-with-profile=production --no-wait